DROP SCHEMA IF EXISTS content CASCADE;
DROP SCHEMA IF EXISTS billing CASCADE;
DROP SCHEMA IF EXISTS clinical CASCADE;
DROP SCHEMA IF EXISTS scheduling CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
